In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

# create and rad 

## 1D Array

In [4]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(4,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim


1

In [9]:
arr1.size

4

#### 2D Array

In [11]:
arr2 = np.array([[1,2,3], [5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape ## (row, col)

(2, 3)

In [14]:
arr2.dtype

dtype('int64')

In [15]:
arr2.size

6

### 3D Array

In [33]:
arr3 = np.array([[[1,2,3]], [[4,5,6]]])
arr3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [34]:
arr3.ndim

3

In [35]:
arr3.shape

(2, 1, 3)

In [36]:
arr3.size

6

# Create Random Array

In [38]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.13767624, 0.14640354, 0.88982253],
        [0.25513885, 0.82014829, 0.38945583]],

       [[0.66344974, 0.70285246, 0.20383679],
        [0.57544546, 0.17662577, 0.84272203]],

       [[0.09474016, 0.56251708, 0.10892578],
        [0.70082615, 0.62278452, 0.082109  ]]])

In [39]:
randomArr.dtype


dtype('float64')

In [40]:
randomArr.size

18

In [42]:
zeroes = np.zeros((3, 2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
zeroes.ndim


3

In [44]:
full = np.full((3, 2, 3),8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [46]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
arr3[0][0]

array([1, 2, 3])

In [49]:
arr3[0][0][2]

np.int64(3)

In [50]:
arr3[0:2]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [51]:
arr3

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [53]:
arr3[1,0]

array([4, 5, 6])

In [55]:
arr3[1,0,2]

np.int64(6)

# Update & Delete 

In [60]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [61]:
a1

array([[[0.8564633 , 0.90635101],
        [0.7683831 , 0.73090695],
        [0.02670511, 0.87058639]],

       [[0.93365464, 0.91121974],
        [0.69601185, 0.37686592],
        [0.08673532, 0.35549895]]])

In [62]:
a2

array([[[0.02421327, 0.61819953],
        [0.29714267, 0.09876702],
        [0.32733007, 0.19921101]],

       [[0.19613836, 0.20860048],
        [0.63247025, 0.96086425],
        [0.82555014, 0.95958092]]])

### Basic Math Operations 

In [63]:
np.add(a1,a2)

array([[[0.88067657, 1.52455054],
        [1.06552577, 0.82967397],
        [0.35403518, 1.0697974 ]],

       [[1.129793  , 1.11982022],
        [1.32848209, 1.33773017],
        [0.91228546, 1.31507987]]])

In [64]:
np.subtract(a1,a2)

array([[[ 0.83225003,  0.28815149],
        [ 0.47124044,  0.63213993],
        [-0.30062496,  0.67137538]],

       [[ 0.73751628,  0.70261927],
        [ 0.0635416 , -0.58399833],
        [-0.73881483, -0.60408197]]])

In [65]:
np.divide(a1,a2)

array([[[35.3716522 ,  1.46611405],
        [ 2.58590633,  7.40031372],
        [ 0.08158465,  4.37017211]],

       [[ 4.76018381,  4.36825341],
        [ 1.10046575,  0.39221557],
        [ 0.10506365,  0.37047313]]])

In [66]:
np.multiply(a1,a2)

array([[[0.02073778, 0.56030577],
        [0.22831941, 0.0721895 ],
        [0.00874139, 0.17343039]],

       [[0.18312549, 0.19008087],
        [0.44020678, 0.36211699],
        [0.07160435, 0.34113001]]])